import Head from 'next/head'
import MainLayout from '../components/layouts/MainLayout';

export default function Home() {
  return (
    <div>
      <Head>
        <title>NotEBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/favicon.ico"} />
      </Head>

        <h1>Main Page</h1>

    </div>
  )
}
