import Head from "next/head";
import MainLayout from "../components/layouts/MainLayout";
import dynamic from 'next/dynamic';

//MUST HAVE TO LOAD
const TextEditor = dynamic(import("../components/layouts/texteditor/TextEditor"), { ssr: false });

export default function Home() {
  return (
    <div>
      <Head>
        <title>NotEBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/favicon.ico"} />
      </Head>
      <h1 className="main__title">TExtBook</h1>

      <TextEditor />
    </div>
  );
}
